cloudeos: Ignore attribute changes in cloudeos resources
* Use SchemaDiffSuppressFunc to suppress unsupported attribute changes
like vtep_ip_cidr, terminattr_ip_cidr etc.
This method is widely used in aws provider to suppress some of the attribute
changes.
https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/diff_suppress_funcs.go

* Fail terraform apply in such cases using log.Fatalf.
Recommend customer to enable traces to find out details fo the error.
Terraform apply output in this case:
Error: rpc error: code = Unavailable desc = transport is closing
In TFLOG, there is detailed error message -
"Attribute change not supported for vtep_ip_cidr, old value: 10.16.10.0/24,
new value: 10.16.10.0/16"

* Alternative to log.Fatalf is log.Panicf, in which case the console error is
the same as above.
Error: rpc error: code = Unavailable desc = transport is closing
Backtrace of panic is visible only in log file.

* Difference between log.Fatalf and log.Panicf is
The log.Panic vs log.Fatal is essentially panic vs os.Exit(1).
The latter will not let deferred calls to run.

* Chose to use log.Fatalf as that is used in aws provider in case of errors

* Please point out more attributes changes that needs to be suppressed as
part of review.

Change-Id: I1c5d17d2269cd26becc17630110aacd25d3c42ac